CREATE DATABASE library;
use library; 

CREATE TABLE librarian (
librarian_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL UNIQUE,
password VARCHAR(100) NOT NULL,
email VARCHAR(200) NOT NULL,
address VARCHAR(200) NOT NULL,
city VARCHAR(100) NOT NULL,
contact VARCHAR(40) NOT NULL
);

CREATE TABLE books (
book_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
callno VARCHAR(100) UNIQUE NOT NULL,
name VARCHAR(100) NOT NULL,
author VARCHAR(100) NOT NULL,
publisher VARCHAR(100) NOT NULL,
quantity INT NOT NULL,
issued INT NOT NULL,
added_date TIMESTAMP NOT NULL
);

CREATE TABLE issue_books (
issuedBook_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
book_call_no VARCHAR(50) NOT NULL,
student_id INT NOT NULL,
student_name VARCHAR(50) NOT NULL,
student_contact VARCHAR(30) NOT NULL,
issued_date TIMESTAMP NOT NULL
);
